config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  resources :posts
  get '/my_posts', to: 'posts#my_posts'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :users, class_name: "User", foreign_key: "users_id"
  scope :active?, -> { where(active: true) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, class_name: 'Post', foreign_key: 'users_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# sends you to home
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_post, only: %i[edit update destroy]

  def index
    @posts = Post.all
    respond_to do |format|
      format.html { render :index, status: :ok }
      format.json { render json: @posts, status: :ok }
    end
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.users_id = current_user.id
    if @post.save
      respond_to do |format|
        format.html { redirect_to posts_path, status: :created, location: @post }
        format.json { render json: @post, status: :created }
      end
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Successfully updated post!'
      respond_to do |format|
        format.html { redirect_to posts_path, status: 303, location: @post }
        format.json { render json: @post, status: :ok }
      end
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_path, status: :ok }
      format.json { head :no_content }
    end
  end

  def my_posts
    @posts = Post.where(users_id: current_user.id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def set_post
    post = Post.find(params[:id])
    if post.users_id == current_user.id
      @post = post
    else
      flash[:alert] = '401 Unauthorized'
      respond_to do |format|
        format.html { redirect_to posts_path, status: :unauthorized }
        format.json { render json: 'UnAuthorized', status: :unauthorized}
      end
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  include SessionsHelper
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<div class="container">
  <h1 style="text-align: center">Hot Posts</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/flash' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<h4>New Post</h4>
<div class="post-form">
  <%= form_with model: @post do |form| %>
    <% if @post.errors.any? %>
      <h4><%= pluralize(@post.errors.count, 'error') %> keeping this post from being saved.</h4>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="form-group">
      <%= form.label :title, class: 'form-label' %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :content, class: 'form-label' %>
      <%= form.text_area :content, class: 'form-control' %>
    </div>
    <%= form.submit 'Save Post', class: 'btn btn-primary mt-3' %>
  <% end %>
</div>

app/views/posts/_list.html.erb
<div class="d-flex flex-column align-items-center">
  <% @posts.each do |post| %>
    <%= render 'post', post: post %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="post">
<h1>Title: <%= post.title %></h1>
<% if !current_user.nil? %>
<h3>Author: <%= post.users.email %></h3>
<% end %>
<p>Content: <%= post.content %></p>
<% if !current_user.nil? && current_user.email == post.users.email %>
  <div class="d-flex">
    <%= link_to 'Edit post', edit_post_path(post), class: 'btn btn-secondary me-2' %>
    <%= button_to 'Delete', post_path(post), method: :delete, class: 'btn btn-danger' %>
  </div>
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <h1 class="me-4 mt-4">All Posts</h1>
  </div>
  <%= render 'list' %>
</div>

app/views/posts/my_posts.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <h1 class="me-4 mt-4">Your Posts</h1>
    <div class="mt-4">
        <%= button_to 'New Post', new_post_path, class: 'btn btn-primary', method: :get %>
    </div>
  </div>
  <%= render 'list' %>
</div>

app/views/posts/new.html.erb
<div class="container d-flex flex-column align-items-center">
  <%= render 'form' %>
</div>

app/views/shared/_flash.html.erb
    <div class="messages">
    <% unless flash[:notice].nil? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% unless flash[:alert].nil? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    </div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Members Only</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="app-navbar" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', posts_path, class: 'nav-link' %>
        </li>
        <li>
          <%= link_to 'Posts', my_posts_path, class: 'nav-link' %>
        </li>
      </ul>

      <ul class="d-flex m-0 navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item"><%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-link' %></li>
        <% else %>
          <li class="nav-item"><%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/user/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/user/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>